/**
 * Fixture dataset — 25 realistic Treasure Valley (Nampa/Boise/Meridian)
 * businesses used by FixturePlacesClient when GOOGLE_PLACES_API_KEY is
 * absent. Covers every Sprint 2 edge case:
 *
 *   - no website            fx-003, fx-008, fx-015, fx-020, fx-024
 *   - social-only URL       fx-004 (facebook), fx-007 (instagram),
 *                           fx-016 (yelp), fx-021 (linktree)
 *   - dead site             fx-005 (host listed in DEAD_FIXTURE_HOSTS)
 *   - builder platforms     fx-002 (wix), fx-012 (godaddy),
 *                           fx-013 (squarespace), fx-014 (wordpress)
 *   - chains                fx-006 (brand list), fx-009/010/011
 *                           (same name ×3 → multi-location detection)
 *   - review extremes       fx-025 (512), fx-017 (4), fx-018 (0, null rating)
 *   - low rating            fx-022 (3.2), fx-016 (3.6)
 *   - missing phone         fx-015, fx-023
 *   - not operational       fx-019 (CLOSED_TEMPORARILY),
 *                           fx-020 (CLOSED_PERMANENTLY)
 *
 * All records sit within ~9 miles of FIXTURE_CENTER so the default 10-mile
 * search returns all 25, while a 5-mile radius demonstrably filters.
 */
import type { LatLng } from "../geo";
import type { PlaceDetails, PlaceRecord } from "./types";

/**
 * Curated Place Details extras (RFL-06) for the fixtures that exercise
 * hours / photos / reviews: fx-001 is complete, fx-002 has partial hours
 * and no reviews. Every other fixture gets a minimal synthesized record.
 */
export const FIXTURE_DETAILS: Readonly<
  Record<string, Partial<Omit<PlaceDetails, "fetchedAt">>>
> = {
  "fx-001": {
    types: ["plumber", "point_of_interest", "establishment"],
    priceLevel: "PRICE_LEVEL_MODERATE",
    editorialSummary: { text: "Family-run plumbing company serving Meridian since 1998." },
    regularOpeningHours: {
      weekdayDescriptions: [
        "Monday: 7:00 AM – 6:00 PM",
        "Tuesday: 7:00 AM – 6:00 PM",
        "Wednesday: 7:00 AM – 6:00 PM",
        "Thursday: 7:00 AM – 6:00 PM",
        "Friday: 7:00 AM – 6:00 PM",
        "Saturday: 8:00 AM – 2:00 PM",
        "Sunday: Closed",
      ],
    },
    photos: [
      { name: "places/fx-001/photos/fxphoto-a", widthPx: 4032, heightPx: 3024 },
      { name: "places/fx-001/photos/fxphoto-b", widthPx: 1600, heightPx: 1200 },
    ],
    reviews: [
      {
        rating: 5,
        text: { text: "Showed up on time and fixed our water heater the same day. Fair price, no upsell." },
        relativePublishTimeDescription: "2 months ago",
        authorAttribution: { displayName: "Dana R." },
      },
      {
        rating: 5,
        text: { text: "Honest plumbers. They explained every option before doing the work." },
        relativePublishTimeDescription: "4 months ago",
        authorAttribution: { displayName: "Mike T." },
      },
      {
        rating: 4,
        text: { text: "Good work on the repipe, a little slow to send the invoice." },
        relativePublishTimeDescription: "a year ago",
        authorAttribution: { displayName: "J. Alvarez" },
      },
    ],
  },
  "fx-002": {
    types: ["plumber", "establishment"],
    regularOpeningHours: {
      weekdayDescriptions: ["Monday: 8:00 AM – 5:00 PM", "Tuesday: 8:00 AM – 5:00 PM"],
    },
    photos: [{ name: "places/fx-002/photos/fxphoto-c", widthPx: 1200, heightPx: 900 }],
  },
};

/** Every fixture zip geocodes here (logged) — Meridian, ID centroid. */
export const FIXTURE_CENTER: LatLng = { lat: 43.6, lng: -116.4 };

/** Hosts the FixtureWebProbe reports as dead ("Site broken — urgent"). */
export const DEAD_FIXTURE_HOSTS: ReadonlySet<string> = new Set([
  "www.oldfaithfulplumbing.com",
]);

export const FIXTURE_BUSINESSES: readonly PlaceRecord[] = [
  {
    placeId: "fx-001",
    name: "Snake River Plumbing Co",
    lat: 43.612,
    lng: -116.392,
    address: "1120 N Main St, Meridian, ID 83642",
    phone: "(208) 555-0101",
    websiteUrl: "https://snakeriverplumbing.com",
    rating: 4.7,
    reviewCount: 127,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-002",
    name: "Boise Drain Pros",
    lat: 43.634,
    lng: -116.279,
    address: "7800 W Fairview Ave, Boise, ID 83704",
    phone: "(208) 555-0102",
    websiteUrl: "https://boisedrainpros.wixsite.com/home",
    rating: 4.5,
    reviewCount: 89,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-003",
    name: "Nampa Rooter & Drain",
    lat: 43.574,
    lng: -116.56,
    address: "223 12th Ave S, Nampa, ID 83651",
    phone: "(208) 555-0103",
    websiteUrl: null,
    rating: 4.8,
    reviewCount: 214,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-004",
    name: "Treasure Valley Plumbing",
    lat: 43.606,
    lng: -116.41,
    address: "2405 E Overland Rd, Meridian, ID 83642",
    phone: "(208) 555-0104",
    websiteUrl: "https://www.facebook.com/treasurevalleyplumbing",
    rating: 4.6,
    reviewCount: 96,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-005",
    name: "Old Faithful Plumbing",
    lat: 43.641,
    lng: -116.3,
    address: "5150 W State St, Boise, ID 83703",
    phone: "(208) 555-0105",
    websiteUrl: "http://www.oldfaithfulplumbing.com",
    rating: 4.2,
    reviewCount: 45,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-006",
    name: "Roto-Rooter Plumbing & Water Cleanup",
    lat: 43.628,
    lng: -116.27,
    address: "6110 W Emerald St, Boise, ID 83704",
    phone: "(208) 555-0106",
    websiteUrl: "https://www.rotorooter.com/boiseid",
    rating: 3.9,
    reviewCount: 342,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-007",
    name: "Gem State Handyman",
    lat: 43.586,
    lng: -116.552,
    address: "16 2nd St S, Nampa, ID 83651",
    phone: "(208) 555-0107",
    websiteUrl: "https://www.instagram.com/gemstatehandyman",
    rating: 4.9,
    reviewCount: 27,
    businessStatus: "OPERATIONAL",
    primaryType: "general_contractor",
  },
  {
    placeId: "fx-008",
    name: "Canyon County Septic",
    lat: 43.565,
    lng: -116.57,
    address: "4808 E Greenhurst Rd, Nampa, ID 83686",
    phone: "(208) 555-0108",
    websiteUrl: null,
    rating: 5.0,
    reviewCount: 8,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-009",
    name: "Boise Plumbing Co",
    lat: 43.615,
    lng: -116.24,
    address: "802 W Bannock St, Boise, ID 83702",
    phone: "(208) 555-0109",
    websiteUrl: "https://boiseplumbingco.com",
    rating: 4.3,
    reviewCount: 61,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-010",
    name: "Boise Plumbing Co",
    lat: 43.64,
    lng: -116.305,
    address: "10400 W Overland Rd, Boise, ID 83709",
    phone: "(208) 555-0110",
    websiteUrl: "https://boiseplumbingco.com/west",
    rating: 4.1,
    reviewCount: 38,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-011",
    name: "Boise Plumbing Co",
    lat: 43.565,
    lng: -116.29,
    address: "2210 S Federal Way, Boise, ID 83705",
    phone: "(208) 555-0111",
    websiteUrl: "https://boiseplumbingco.com/south",
    rating: 4.4,
    reviewCount: 22,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-012",
    name: "Meridian Comfort Heating & Air",
    lat: 43.6,
    lng: -116.38,
    address: "3327 N Eagle Rd, Meridian, ID 83646",
    phone: "(208) 555-0112",
    websiteUrl: "https://meridiancomfort.godaddysites.com",
    rating: 4.4,
    reviewCount: 52,
    businessStatus: "OPERATIONAL",
    primaryType: "hvac_contractor",
  },
  {
    placeId: "fx-013",
    name: "Kuna Electric",
    lat: 43.492,
    lng: -116.42,
    address: "751 W Main St, Kuna, ID 83634",
    phone: "(208) 555-0113",
    websiteUrl: "https://kunaelectric.squarespace.com",
    rating: 4.9,
    reviewCount: 19,
    businessStatus: "OPERATIONAL",
    primaryType: "electrician",
  },
  {
    placeId: "fx-014",
    name: "Star Plumbing & Heating",
    lat: 43.69,
    lng: -116.49,
    address: "10940 W State St, Star, ID 83669",
    phone: "(208) 555-0114",
    websiteUrl: "https://starplumbingidaho.wordpress.com",
    rating: 4.1,
    reviewCount: 73,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-015",
    name: "Eagle Rapid Rooter",
    lat: 43.698,
    lng: -116.352,
    address: "50 E State St, Eagle, ID 83616",
    phone: null,
    websiteUrl: null,
    rating: 4.6,
    reviewCount: 156,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-016",
    name: "Canyon Sewer Solutions",
    lat: 43.59,
    lng: -116.575,
    address: "1503 1st St S, Nampa, ID 83651",
    phone: "(208) 555-0116",
    websiteUrl: "https://www.yelp.com/biz/canyon-sewer-solutions-nampa",
    rating: 3.6,
    reviewCount: 41,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-017",
    name: "Idaho Pipe Dream Plumbing",
    lat: 43.65,
    lng: -116.28,
    address: "4720 W Chinden Blvd, Garden City, ID 83714",
    phone: "(208) 555-0117",
    websiteUrl: "https://pipedreamidaho.webflow.io",
    rating: 5.0,
    reviewCount: 4,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-018",
    name: "Meridian Water Heater Repair",
    lat: 43.62,
    lng: -116.4,
    address: "1830 W Franklin Rd, Meridian, ID 83642",
    phone: "(208) 555-0118",
    websiteUrl: "https://meridianwaterheater.com",
    rating: null,
    reviewCount: 0,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-019",
    name: "ABC Plumbing of Boise",
    lat: 43.63,
    lng: -116.25,
    address: "1420 N Orchard St, Boise, ID 83706",
    phone: "(208) 555-0119",
    websiteUrl: "https://abcplumbingboise.com",
    rating: 4.0,
    reviewCount: 88,
    businessStatus: "CLOSED_TEMPORARILY",
    primaryType: "plumber",
  },
  {
    placeId: "fx-020",
    name: "Sunset Plumbing & Drain",
    lat: 43.58,
    lng: -116.545,
    address: "824 Sunset Ave, Nampa, ID 83651",
    phone: "(208) 555-0120",
    websiteUrl: null,
    rating: 4.5,
    reviewCount: 112,
    businessStatus: "CLOSED_PERMANENTLY",
    primaryType: "plumber",
  },
  {
    placeId: "fx-021",
    name: "Linktree Lawn & Sprinkler",
    lat: 43.595,
    lng: -116.37,
    address: "2820 S Meridian Rd, Meridian, ID 83642",
    phone: "(208) 555-0121",
    websiteUrl: "https://linktr.ee/tvlawnsprinkler",
    rating: 4.7,
    reviewCount: 15,
    businessStatus: "OPERATIONAL",
    primaryType: "landscaper",
  },
  {
    placeId: "fx-022",
    name: "Vista Heating & Cooling",
    lat: 43.585,
    lng: -116.245,
    address: "2109 S Vista Ave, Boise, ID 83705",
    phone: "(208) 555-0122",
    websiteUrl: "https://vistaheatcool.com",
    rating: 3.2,
    reviewCount: 240,
    businessStatus: "OPERATIONAL",
    primaryType: "hvac_contractor",
  },
  {
    placeId: "fx-023",
    name: "Garden City Garage & Door",
    lat: 43.655,
    lng: -116.29,
    address: "3663 W Adams St, Garden City, ID 83714",
    phone: null,
    websiteUrl: "https://gcgaragedoor.com",
    rating: 4.2,
    reviewCount: 34,
    businessStatus: "OPERATIONAL",
    primaryType: "general_contractor",
  },
  {
    placeId: "fx-024",
    name: "Ten Mile Plumbing LLC",
    lat: 43.577,
    lng: -116.425,
    address: "4886 W Franklin Rd, Meridian, ID 83642",
    phone: "(208) 555-0124",
    websiteUrl: null,
    rating: 4.3,
    reviewCount: 31,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
  {
    placeId: "fx-025",
    name: "Precision Plumbing Idaho",
    lat: 43.61,
    lng: -116.26,
    address: "980 S Capitol Blvd, Boise, ID 83702",
    phone: "(208) 555-0125",
    websiteUrl: "https://precisionplumbingidaho.com",
    rating: 4.9,
    reviewCount: 512,
    businessStatus: "OPERATIONAL",
    primaryType: "plumber",
  },
];
